### ISSUE TITLE
Compile QSimpleScada

### ISSUE THREAD

**Issue by Ahrovan** [IndeemaSoftware/QSimpleScada#1]
Hi,
after build QSimpleScada with qt in windows can not find QSimpleScadaLib folder, and how to add QSimpleScadaLib to QSimpleScadaSample project.

thanks

**Comment by vshevchyk** [comment]
Hello,

The easiest way to run QSimpleScadaSample is to use qpm. Just run qpm install inside QSimpleScadaSample and QSimpleScada will be downloaded and installed in vendor folder. After that you can compile sample.

Regarding lib folder it will be in the same path with QSimpleScada 
//in pro file
win32 {
    DLLDESTDIR +=../QSimpleScadaLib/
}


Regarding how to add lib to QSimpleScadaSample, just connect dll and hearers in pro file and remove line - include(com_indeema_QSimpleScada.pri) - from pro file.

**Comment by Ahrovan** [comment]
```
QSimpleScada-master>qpm install
QPM: 2018/12/22 16:01:48 ERROR: rpc error: code = 3 desc = Must supply at least one package

```
and
```
QSimpleScadaSample-master>qpm install
QPM: 2018/12/22 16:02:28 ERROR: No qpm.json file found
```

**Comment by vshevchyk** [comment]
in QSimapleScadaSample run
qpm install com.indeema.QSimpleScada


or now just run 
qpm install 

I've added qpm file.

**Comment by Ahrovan** [comment]
**in QSimpleScada-master dir, I opened QSimpleScada.pro and build qt project:**
```
16:33:05: Running steps for project QSimpleScada...
16:33:05: Configuration unchanged, skipping qmake step.
16:33:05: Starting: "C:\Qt\Qt5.9.0\Tools\mingw530_32\bin\mingw32-make.exe" 
C:/Qt/Qt5.9.0/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'E:/Design/QSimpleScada-master/build-QSimpleScada-Desktop_Qt_5_9_0_MinGW_32bit-Debug'
mingw32-make[1]: Nothing to be done for 'first'.
mingw32-make[1]: Leaving directory 'E:/Design/QSimpleScada-master/build-QSimpleScada-Desktop_Qt_5_9_0_MinGW_32bit-Debug'
16:33:07: The process "C:\Qt\Qt5.9.0\Tools\mingw530_32\bin\mingw32-make.exe" exited normally.
16:33:07: Elapsed time: 00:02.
```
QSimpleScada0.dll created in QSimpleScada-master\QSimpleScadaLib\.
**then as you say:**
```
QSimpleScadaSample-master\QSimpleScadaSample-master>qpm install com.indeema.QSimpleScada
INFO: Package com.indeema.qsimplescada has a different license (MIT) than it's dependant (NONE).
Installing com.indeema.qsimplescada@0.5.0

QSimpleScadaSample-master\QSimpleScadaSample-master>qpm install
INFO: Package com.indeema.qsimplescada has a different license (MIT) than it's dependant (NONE).
Installing com.indeema.qsimplescada@0.5.0

QSimpleScadaSample-master\QSimpleScadaSample-master>
```
**now vender <DIR> added:**
```
12/22/2018  04:35 PM    <DIR>          .
12/22/2018  04:35 PM    <DIR>          ..
09/11/2018  09:45 PM               172 main.cpp
09/11/2018  09:45 PM             7,403 mainwindow.cpp
09/11/2018  09:45 PM               822 mainwindow.h
09/11/2018  09:45 PM             2,180 mainwindow.ui
12/22/2018  04:35 PM                64 qpm.json
09/11/2018  09:45 PM             1,081 QSimpleScadaSample.pro
09/11/2018  09:45 PM             1,377 README.md
09/11/2018  09:45 PM    <DIR>          resources
09/11/2018  09:45 PM               107 resources.qrc
12/22/2018  04:35 PM    <DIR>          vendor
               8 File(s)         13,206 bytes
               4 Dir(s)  46,477,438,976 bytes free
```
then open QSimpleScadaSample.pro with qt

also I added 
```
win32 {
DLLDESTDIR +=../QSimpleScadaLib/
}
```
to QSimpleScadaSample.pro file.

**Result:**
`E:\Design\QSimpleScadaSample-master\QSimpleScadaSample-master\vendor\com\indeema\qsimplescada\QScadaBoard\qscadaboardcontroller.h:7: error: ../QScadaObject/qscadaobject.h: No such file or directory`
**but now I don't know why error occur.**

**Comment by vshevchyk** [comment]
You don't need to compile QSimpleScada as dll if you are using qpm. QPM downloads code from github and locates in vendor folder.

You should use custom compilation or qpm.
If custom compilation then you also nee to add headers to your project.

win32 {
DLLDESTDIR +=../QSimpleScadaLib/
INCLUDPATH += ../QSimpleScada
}

I reccomend to use qpm. so remove win32 from profile.

**Comment by Ahrovan** [comment]
include(com_indeema_QSimpleScada.pri) is Only in QSimpleScada.pro project that was built with qt and QSimpleScada0.dll created. I have previously worked with qt. I don't know the relationship between the two projects. 

qpm created C:\Users\USER\vendor, I see C:\Users\USER\vendor\com\indeema\qsimplescada.

**I went the way you said with qpm**. Please guide for that. now I do not work with the project QSimpleScada for custom compilation

**Comment by Ahrovan** [comment]
I removed:
win32 {
DLLDESTDIR +=../QSimpleScadaLib/
}
my qt project :
![image](https://user-images.githubusercontent.com/5772832/50374914-5f4f8f80-060a-11e9-8193-9ed5c372ad1d.png)

**Comment by vshevchyk** [comment]
Did you remove shadow build folder before compilation?

**Comment by Ahrovan** [comment]
no, There is no such folder name in sample files 
If you mean the folder ؛build-QSimpleScadaSample-Desktop_Qt_5_9_0_MinGW_32bit-Debug؛ Yes I try remove that and rebuild project again

**Comment by vshevchyk** [comment]
Could you copy here the whole error, as it's cutted on screenshot

**Comment by Ahrovan** [comment]
![image](https://user-images.githubusercontent.com/5772832/50375014-27e1e280-060c-11e9-9b1d-87ba0282c17f.png)

and .pro file:

```
#-------------------------------------------------
#
# Project created by QtCreator 2017-07-01T17:39:42
#
#-------------------------------------------------

QT       += core gui network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = QSimpleScadaSample
TEMPLATE = app
CONFIG +=C++14

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

include (./vendor/vendor.pri)

SOURCES += main.cpp\
        mainwindow.cpp

HEADERS  += mainwindow.h

RESOURCES += resources.qrc

FORMS += mainwindow.ui

```

**Comment by vshevchyk** [comment]
I just checked on my machine, it's working fine.

It looks like INCLUDEPATH += $$PWD in QSimpleScada pri file is not working

**Comment by vshevchyk** [comment]
Also please check if all files where download correctly

<img width="477" alt="screen shot 2018-12-22 at 3 57 43 pm" src="https://user-images.githubusercontent.com/2978800/50375201-5bb80a80-0602-11e9-94dc-2a91feed8c39.png">

**Comment by Ahrovan** [comment]
![image](https://user-images.githubusercontent.com/5772832/50375277-18fd2f00-0610-11e9-9d97-d3a79e58f6d3.png)
I do not know why my folder is very different from the contents of your folder.
The contents after running the following two commands were added. Unless you have done another way to add this folder:
```
QSimpleScadaSample-master>qpm install com.indeema.QSimpleScada
QSimpleScadaSample-master>qpm install
```
I checked but don't know why ..
![image](https://user-images.githubusercontent.com/5772832/50375386-8d849d80-0611-11e9-8db3-a7d20eb96357.png)

**Comment by Ahrovan** [comment]
I changed project dir to C:/ and rebuild. problem solved.

**Comment by vshevchyk** [comment]
Super, I am happy to hear that.  Please mark this issue solved
